from __future__ import annotations

import json
import os
import sys
from typing import Any, Dict, List

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "validation")
RESULTS = os.path.join(OUT, "results")


def load(path: str, default: Any = None) -> Any:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError):
        return default


def write(name: str, text: str) -> None:
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as handle:
        handle.write(text.rstrip("\n") + "\n")


def cell(value: Any, limit: int = 90) -> str:
    text = str(value if value is not None else "").replace("|", "\\|").replace("\n", " ")
    return text if len(text) <= limit else text[: limit - 1] + "…"


def table(headers: List[str], rows: List[List[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(cell(c) for c in row) + " |")
    return "\n".join(lines)


def inventory_md(inv: Dict[str, Any]) -> str:
    counts = inv["counts"]
    parts = [
        "# RTSA full inventory (source-derived)",
        "",
        f"Generated by `validation/tools/inventory.py` from the checked-out repository (`{inv['git_head'][:12]}`), using AST analysis plus runtime discovery. "
        "Nothing in this file was typed by hand; re-run the tool to refresh it.",
        "",
        "## Counts",
        "",
        table(["Item", "Count"], [[k, v] for k, v in counts.items()]),
        "",
        f"Static and runtime command discovery agree: **{inv['command_discovery_consistent']}** "
        f"(only static: {inv['commands_only_static'] or 'none'}, only runtime: {inv['commands_only_runtime'] or 'none'}).",
        "",
        "## Slash commands",
        "",
    ]
    rows = []
    for c in inv["commands"]:
        kinds = c["sinks"].get("kinds", {})
        rows.append([
            f"/{c['name']}", c["auth_effective"], ", ".join(p["name"] for p in c["parameters"]) or "-", ",".join(f"{k}:{v}" for k, v in kinds.items() if k in ("SUBPROCESS", "FS_WRITE", "FS_DELETE", "NETWORK", "PROC_CONTROL", "DB_WRITE", "SUDO")) or "-",
            ", ".join(c["sinks"].get("executables", [])[:5]) or "-", ", ".join(c["views"]) or "-", ", ".join(c["locks"][:2]) or "-",
        ])
    parts.append(table(["Command", "Authorization (effective)", "Parameters", "Reachable side-effect sinks (static, approximate)", "External executables", "Views", "Locks"], rows))
    parts += ["", "Authorization tiers: `admin` = `admin_role_ids`; `critical` = `critical_command_role_ids` (falls back to admin); `NONE` = no check in any reachable function.", "", "## Interactive components", ""]
    rows = []
    for comp in inv["ui_components"]:
        rows.append([comp["class"], comp["file"], comp["timeout"] or "-", "yes" if comp["has_interaction_check"] else "NO", "; ".join(f"{b['label']}" for b in comp["buttons"]) or "-"])
    parts.append(table(["View class", "File", "Timeout", "interaction_check", "Buttons"], rows))
    a = inv["alert_actions"]
    parts += ["", "## Alert (webhook) action buttons", "", f"Emitted `rtsa_action:<action>:<event_id>` ids: **{len(a['emitted'])}** — {', '.join(a['emitted'])}.", "",
              f"Handled directly by `on_interaction`: {', '.join(a['handled_in_on_interaction'])}.", "",
              f"Emitted but not directly handled: {a['emitted_but_not_directly_handled'] or 'none'}. Handled but never emitted (dead handler): {a['handled_but_never_emitted'] or 'none'}.", "",
              "## Modules (BaseModule implementations)", ""]
    rows = []
    for m in inv["modules"]:
        rows.append([m["module_name"], m["class"], m["config_attr"], m["enabled_by_default"], m["loc"], len(m["subscribes"]), len(m["mentions_categories"]), ",".join(f"{k}:{v}" for k, v in m["sink_counts"].items() if k in ("SUBPROCESS", "FS_WRITE", "FS_DELETE", "NETWORK", "PROC_CONTROL", "TASK_SPAWN", "THREAD_POOL")) or "-", ", ".join(m["executables"][:5]) or "-"])
    parts.append(table(["Module", "Class", "Config attr", "Default on", "LOC", "Subscribed categories", "Categories referenced", "Sinks", "Executables"], rows))
    parts += ["", f"Runtime discovery (`main.discover_modules`) found {len(inv['modules_runtime'])} modules: {', '.join(m['name'] for m in inv['modules_runtime'])}.", "", "## Core components", ""]
    rows = []
    for c in inv["core_components"]:
        if c["file"].startswith("core/"):
            rows.append([c["file"], c["loc"], c["functions"], c["imported_by_count"], ",".join(f"{k}:{v}" for k, v in c["sink_counts"].items() if k in ("SUBPROCESS", "FS_WRITE", "FS_DELETE", "NETWORK", "PROC_CONTROL")) or "-", ", ".join(c["executables"][:4]) or "-"])
    parts.append(table(["File", "LOC", "Functions", "Imported by", "Sinks", "Executables"], rows))
    cats = inv["event_categories"]
    parts += ["", "## Event categories", "", f"{cats['count']} categories. Unreferenced anywhere outside `datatypes.py`: {cats['unreferenced'] or 'none'}.", "",
              "## Fast polling and task spawning", "", f"`asyncio.sleep` constants <= 2 s: {len(inv['polling_and_tasks']['fast_sleeps_le_2s'])} sites; `create_task`/`ensure_future` sites: {len(inv['polling_and_tasks']['task_spawn_sites'])}.", ""]
    rows = [[f"{x['file']}:{x['line']}", x["seconds"]] for x in inv["polling_and_tasks"]["fast_sleeps_le_2s"]]
    parts.append(table(["Site", "Seconds"], rows))
    return "\n".join(parts)


def gaps_md(inv: Dict[str, Any]) -> str:
    tests = inv["tests"]
    no_cmd = [n for n, t in tests["commands"].items() if not t]
    parts = [
        "# RTSA test coverage gaps (source-derived)",
        "",
        "Mapping is textual (a test file counts as covering a command/module/core file when it references it by name or import), so it over-states real coverage: a reference is not an assertion of behaviour. "
        "Unit tests that only assert on mocks are listed under *mock-heavy files*.",
        "",
        f"* Test files in the suite: **{tests['test_files']}**; lab/benchmark scripts outside the suite: {', '.join(tests['lab_files'])}.",
        f"* Slash commands with **no test reference**: **{len(no_cmd)} of {len(tests['commands'])}** — {', '.join('/' + n for n in no_cmd)}.",
        f"* Modules with no test reference: {[n for n, t in tests['modules'].items() if not t] or 'none'}.",
        f"* Core/database/config files with no test reference: {[n for n, t in tests['core'].items() if not t] or 'none'}.",
        "",
        "## Commands by number of referencing tests",
        "",
        table(["Command", "Auth", "Referencing tests"], [[f"/{c['name']}", c["auth_effective"], len(tests["commands"].get(c["name"], []))] for c in sorted(inv["commands"], key=lambda c: len(tests["commands"].get(c["name"], [])))]),
        "",
        "## Modules by number of referencing tests",
        "",
        table(["Module", "Referencing tests"], [[n, len(t)] for n, t in sorted(tests["modules"].items(), key=lambda kv: len(kv[1]))]),
        "",
        "## Dimensions with no suite-level test (from the validation campaign)",
        "",
        "See `RTSA_VALIDATION_MATRIX.md` for rows marked `NOT TESTED` and the reason.",
    ]
    return "\n".join(parts)


def command_coverage_md(inv: Dict[str, Any]) -> str:
    campaign = load(os.path.join(RESULTS, "command_campaign.json"), {})
    parts = ["# RTSA command coverage", "",
             "One row per slash command discovered by AST and by runtime registration (they agree). Columns after *Tests* are results of the executable command campaign "
             "(`validation/tools/command_campaign.py`, summarised by `campaign_summary.py`). It invokes the real registered callbacks of a real `RTSABot` with fake Discord "
             "interactions against the 127-project sandbox estate, and intercepts every subprocess, file write/delete/chmod/chown, signal, DNS lookup, network connect and "
             "DB write (Python audit hook plus asyncio subprocess fakes). Mutations are recorded and blocked; nothing reached the host.", "",
             "Caller classes per command: roles not configured, member without RTSA roles, DM user (not a guild member), admin-only member, critical member, critical member with "
             "`detection_only: true`, another member clicking the confirm button, and two concurrent invocations. Hostile input classes per free-text parameter: shell "
             "metacharacters (`;`, `$()`, backticks, `|`), path traversal, absolute path, leading-dash option, newline, CRLF, NUL, 4 KiB overlong, Unicode confusable + RTL "
             "override, glob, space, empty, format string, `@everyone`, role mention; integer parameters get negative, zero, out-of-range and int64 values.", ""]
    if not campaign:
        parts.append("_Campaign results not generated yet._")
        return "\n".join(parts)
    totals = campaign.get("totals", {})
    parts += [f"**Commands discovered:** {totals.get('commands_discovered')} · **executed:** {totals.get('commands_tested')} · **cases:** {totals.get('cases')} · "
              f"**verdicts:** {totals.get('verdicts')} · **alert-button cases:** {totals.get('alert_cases')} ({totals.get('alert_verdicts')})", ""]
    rows = []
    for c in inv["commands"]:
        res = campaign.get("commands", {}).get(c["name"], {})
        rob = res.get("robustness") or {}
        rob_text = ", ".join(f"{k}:{v}" for k, v in rob.items() if v) or "clean"
        rows.append([
            f"/{c['name']}", res.get("tier", c["auth_effective"]), len(inv["tests"]["commands"].get(c["name"], [])), res.get("cases", "-"), res.get("unauthorized", "-"),
            res.get("side_effects_unauthorized", "-"), res.get("injection", "-"), res.get("detection_only", "-"), res.get("confirm_gate", "-"), res.get("concurrency", "-"),
            res.get("components", "-"), rob_text, res.get("verdict", "NOT TESTED"),
        ])
    parts.append(table(["Command", "Tier", "Suite tests", "Cases", "Unauthorized callers", "Side effects (unauth)", "Hostile input", "detection_only", "Confirm gate",
                        "2x concurrent", "Buttons (other member)", "Robustness", "Verdict"], rows))
    alerts = campaign.get("alerts") or {}
    if alerts:
        parts += ["", "## Alert action buttons (`rtsa_action:<action>:<event_id>`)", "",
                  "Each action was clicked by a member without roles, a DM user, an admin-only member and a critical member on a seeded incident; by a critical member with "
                  "`detection_only: true`; on an incident whose stored target is protected (pid 1, port 22, `ssh.service`, user `root`, PM2 app `all`); on an incident "
                  "with no target fields and on a missing incident; then replayed on the same message in the same process and after a simulated restart.", ""]
        rows = []
        for name, a in sorted(alerts.items()):
            rows.append([name, a["cases"], a["unauthorized"], a["detection_only"], a["protected_target"], a["replay_same_process"], a["replay_after_restart"], a["exceptions"], a["verdict"]])
        parts.append(table(["Action", "Cases", "Unauthorized", "detection_only", "Protected target", "Replay (same process)", "Replay after restart", "Exceptions", "Verdict"], rows))
    details = [(n, r) for n, r in campaign.get("commands", {}).items() if r.get("failures") or r.get("notes")]
    if details:
        parts += ["", "## Failures and notes per command", ""]
        for name, r in sorted(details):
            parts.append(f"### /{name} — {r['verdict']}")
            for f in r.get("failures", []):
                parts.append(f"- FAIL: {cell(f, 400)}")
            for n in r.get("notes", []):
                parts.append(f"- note: {cell(n, 400)}")
            parts.append("")
    alert_details = [(n, a) for n, a in alerts.items() if a.get("failures") or a.get("notes")]
    if alert_details:
        parts += ["## Failures and notes per alert action", ""]
        for name, a in sorted(alert_details):
            parts.append(f"### {name} — {a['verdict']}")
            for f in a.get("failures", [])[:6]:
                parts.append(f"- FAIL: {cell(f, 400)}")
            for n in a.get("notes", [])[:4]:
                parts.append(f"- note: {cell(n, 400)}")
            parts.append("")
    return "\n".join(parts)


def feature_coverage_md(inv: Dict[str, Any]) -> str:
    tests = inv["tests"]
    parts = ["# RTSA feature coverage", "", "Modules, core components, alert actions and event categories with the number of suite test files that reference them and the validation-campaign status.", ""]
    rows = [[m["module_name"], m["file"], len(tests["modules"].get(m["module_name"], [])), "see RTSA_FALSE_POSITIVE_FALSE_NEGATIVE.md"] for m in inv["modules"]]
    parts.append(table(["Module", "File", "Referencing tests", "Adversarial matrix"], rows))
    parts += ["", "## Core components", ""]
    rows = [[c["file"], c["imported_by_count"], len(tests["core"].get(c["file"], []))] for c in inv["core_components"] if c["file"].startswith("core/")]
    parts.append(table(["Core file", "Imported by (files)", "Referencing tests"], rows))
    return "\n".join(parts)


def main() -> None:
    inv = load(os.path.join(OUT, "RTSA_FULL_INVENTORY.json"))
    if inv is None:
        print("inventory missing; run inventory.py first")
        sys.exit(1)
    write("RTSA_FULL_INVENTORY.md", inventory_md(inv))
    write("RTSA_TEST_COVERAGE_GAPS.md", gaps_md(inv))
    write("RTSA_COMMAND_COVERAGE.md", command_coverage_md(inv))
    write("RTSA_FEATURE_COVERAGE.md", feature_coverage_md(inv))
    print("rendered")


if __name__ == "__main__":
    main()
